In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression

true = pd.read_csv('True.csv')
fake = pd.read_csv('Fake.csv')

# first 5 rows of true news
true.head()

                                               title  ...                date
0  As U.S. budget fight looms, Republicans flip t...  ...  December 31, 2017
1  U.S. military to accept transgender recruits o...  ...  December 29, 2017
2  Senior U.S. Republican senator: 'Let Mr. Muell...  ...  December 31, 2017
3  FBI Russia probe helped by Australian diplomat...  ...  December 30, 2017
4  Trump wants Postal Service to charge 'much mor...  ...  December 29, 2017

[5 rows x 4 columns]

In [ ]:
# first 5 rows of false/fake news
fake.head()

                                               title  ...               date
0   Donald Trump Sends Out Embarrassing New Year’...  ...  December 31, 2017
1   Drunk Bragging Trump Staffer Started Russian ...  ...  December 31, 2017
2   Sheriff David Clarke Becomes An Internet Joke...  ...  December 30, 2017
3   Trump Is So Obsessed He Even Has Obama’s Name...  ...  December 29, 2017
4   Pope Francis Just Called Out Donald Trump Dur...  ...  December 25, 2017

[5 rows x 4 columns]

In [ ]:
# creating a label to indicate if a news is true or fake
true['label']=1 #true
fake['label']=0 #fake

In [ ]:
true.head()

                                               title  ... label
0  As U.S. budget fight looms, Republicans flip t...  ...     1
1  U.S. military to accept transgender recruits o...  ...     1
2  Senior U.S. Republican senator: 'Let Mr. Muell...  ...     1
3  FBI Russia probe helped by Australian diplomat...  ...     1
4  Trump wants Postal Service to charge 'much mor...  ...     1

[5 rows x 5 columns]

In [ ]:
fake.head()

                                               title  ... label
0   Donald Trump Sends Out Embarrassing New Year’...  ...     0
1   Drunk Bragging Trump Staffer Started Russian ...  ...     0
2   Sheriff David Clarke Becomes An Internet Joke...  ...     0
3   Trump Is So Obsessed He Even Has Obama’s Name...  ...     0
4   Pope Francis Just Called Out Donald Trump Dur...  ...     0

[5 rows x 5 columns]

In [ ]:
#merging the two tables row wise
news = pd.concat([fake,true],axis=0) # since row wise thus axis=0
news.head()

                                               title  ... label
0   Donald Trump Sends Out Embarrassing New Year’...  ...     0
1   Drunk Bragging Trump Staffer Started Russian ...  ...     0
2   Sheriff David Clarke Becomes An Internet Joke...  ...     0
3   Trump Is So Obsessed He Even Has Obama’s Name...  ...     0
4   Pope Francis Just Called Out Donald Trump Dur...  ...     0

[5 rows x 5 columns]

In [ ]:
news.tail()

                                                   title  ... label
21412  'Fully committed' NATO backs new U.S. approach...  ...     1
21413  LexisNexis withdrew two products from Chinese ...  ...     1
21414  Minsk cultural hub becomes haven from authorities  ...     1
21415  Vatican upbeat on possibility of Pope Francis ...  ...     1
21416  Indonesia to buy $1.14 billion worth of Russia...  ...     1

[5 rows x 5 columns]

In [ ]:
# no. of rows and columns in new table
news.shape

(44898, 5)

In [ ]:
# info about the data
news.describe()

              label
count  44898.000000
mean       0.477015
std        0.499477
min        0.000000
25%        0.000000
50%        0.000000
75%        1.000000
max        1.000000

In [ ]:
# check if there are any missing values
news.isnull().sum()

title      0
text       0
subject    0
date       0
label      0
dtype: int64

In [ ]:
# the title, subject and date columns are not needed in this project
news = news.drop(['title','subject','date'],axis=1)
news.head()

                                                text  label
0  Donald Trump just couldn t wish all Americans ...      0
1  House Intelligence Committee Chairman Devin Nu...      0
2  On Friday, it was revealed that former Milwauk...      0
3  On Christmas day, Donald Trump announced that ...      0
4  Pope Francis used his annual Christmas Day mes...      0

In [ ]:
# reshuffling the data so the model is not biased since now in the upper half we have fake news and at the bottom we have true news
news = news.sample(frac=1)
news.head()

                                                    text  label
11607  YAOUNDE (Reuters) - A Cameroonian journalist j...      1
9436   GENEVA (Reuters) - U.S. Republican presidentia...      1
283    Again, these are AMERICAN citizens he is talki...      0
20371  HAVANA (Reuters) - President Raul Castro calle...      1
11332  TOKYO (Reuters) - Japanese police said on Wedn...      1

In [ ]:
# but now the indices are wrong so to fix that
news.reset_index(inplace=True)

In [ ]:
news.head()

   index                                               text  label
0  11607  YAOUNDE (Reuters) - A Cameroonian journalist j...      1
1   9436  GENEVA (Reuters) - U.S. Republican presidentia...      1
2    283  Again, these are AMERICAN citizens he is talki...      0
3  20371  HAVANA (Reuters) - President Raul Castro calle...      1
4  11332  TOKYO (Reuters) - Japanese police said on Wedn...      1

In [ ]:
news = news.drop(columns='index',axis=1)
news.head()

                                                text  label
0  YAOUNDE (Reuters) - A Cameroonian journalist j...      1
1  GENEVA (Reuters) - U.S. Republican presidentia...      1
2  Again, these are AMERICAN citizens he is talki...      0
3  HAVANA (Reuters) - President Raul Castro calle...      1
4  TOKYO (Reuters) - Japanese police said on Wedn...      1

In [ ]:
import re
# some words and their context is important
def wordopt(text):
  text = text.lower() # convert to lowercase

  text = re.sub(r'https?://\S+|www\.\S+','',text) # remove urls

  text = re.sub(r'[^\w\s]','',text)   # remove punctuation

  text = re.sub(r'\d','',text)   # remove digits

  text = re.sub(r'\n','',text)  # remove newline characters

  return text

In [ ]:
news['text'] = news['text'].apply(wordopt)

In [ ]:
news['text']

0        yaounde reuters  a cameroonian journalist jail...
1        geneva reuters  us republican presidential can...
2        again these are american citizens he is talkin...
3        havana reuters  president raul castro called o...
4        tokyo reuters  japanese police said on wednesd...
                               ...
44893    seoulbeijing reuters  south korea will never t...
44894    washington reuters  the republican chairman of...
44895    the most controversial judicial nominee on pre...
44896    can you imagine being potus and having this th...
44897    united nations reuters  a subtle diplomat like...
Name: text, Length: 44898, dtype: object

In [ ]:
# defining x and y i.e. independent and dependent variable
x = news['text']
y = news['label']

# split data
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=2)

In [ ]:
# converting the textual data into numerical data
from sklearn.feature_extraction.text import TfidfVectorizer
vectorization = TfidfVectorizer()
xv_train = vectorization.fit_transform(x_train)
xv_test = vectorization.transform(x_test)

In [ ]:
#train the model
# logistic regression
lr = LogisticRegression()
lr.fit(xv_train,y_train)
print("Training accuracy : ",accuracy_score(lr.predict(xv_train),y_train))
print("Testing accuracy : ",accuracy_score(lr.predict(xv_test),y_test))

Training accuracy :  0.993095329005982
Testing accuracy :  0.9881217520415738
Training accuracy :  1.0
Testing accuracy :  0.995916852264291

In [ ]:
# decision tree classifier
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(xv_train,y_train)
print("Training accuracy : ",accuracy_score(dtc.predict(xv_train),y_train))
print("Testing accuracy : ",accuracy_score(dtc.predict(xv_test),y_test))

Training accuracy :  1.0
Testing accuracy :  0.9961395694135116

In [ ]:
# random forest classifier
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(random_state=0)
rfc.fit(xv_train,y_train)
print("Training accuracy : ",accuracy_score(rfc.predict(xv_train),y_train))
print("Testing accuracy : ",accuracy_score(rfc.predict(xv_test),y_test))

Training accuracy :  1.0
Testing accuracy :  0.985894580549369

In [ ]:
# gradient boosting classifier
from sklearn.ensemble import GradientBoostingClassifier
gbc = GradientBoostingClassifier(random_state=0)
gbc.fit(xv_train,y_train)
print("Training accuracy : ",accuracy_score(gbc.predict(xv_train),y_train))
print("Testing accuracy : ",accuracy_score(gbc.predict(xv_test),y_test))

Training accuracy :  0.9971044928089602
Testing accuracy :  0.995916852264291

In [ ]:
# prediction making for input data

def manual_testing(news):
  testing_news = {"text":[news]}
  new_def_test = pd.DataFrame(testing_news)
  new_def_test["text"] = new_def_test["text"].apply(wordopt)
  new_x_test = new_def_test["text"]
  new_xv_test = vectorization.transform(new_x_test)
  pred_LR = lr.predict(new_xv_test)
  pred_gbc = gbc.predict(new_xv_test)
  pred_rfc = rfc.predict(new_xv_test)
  return "\n\nLR Prediction : {}\nGBC Prediction : {}\nRFC Prediction : {}".format(
      output_label(pred_LR[0]),output_label(pred_gbc[0]),output_label(pred_rfc[0]))

In [ ]:
def output_label(n):
  if n==0:
    return "It is fake news"
  elif n==1:
    return "It is a genuine news"

In [ ]:
news_article = str(input("What's the news ??!! : "))

What's the news ??!! : WASHINGTON (Reuters) - The head of a conservative Republican faction in the U.S. Congress, who voted this month for a huge expansion of the national debt to pay for tax cuts, called himself a “fiscal conservative” on Sunday and urged budget restraint in 2018. In keeping with a sharp pivot under way among Republicans, U.S. Representative Mark Meadows, speaking on CBS’ “Face the Nation,” drew a hard line on federal spending, which lawmakers are bracing to do battle over in January. When they return from the holidays on Wednesday, lawmakers will begin trying to pass a federal budget in a fight likely to be linked to other issues, such as immigration policy, even as the November congressional election campaigns approach in which Republicans will seek to keep control of Congress. President Donald Trump and his Republicans want a big budget increase in military spending, while Democrats also want proportional increases for non-defense “discretionary” spending on programs that support education, scientific research, infrastructure, public health and environmental protection. “The (Trump) administration has already been willing to say: ‘We’re going to increase non-defense discretionary spending ... by about 7 percent,’” Meadows, chairman of the small but influential House Freedom Caucus, said on the program. “Now, Democrats are saying that’s not enough, we need to give the government a pay raise of 10 to 11 percent. For a fiscal conservative, I don’t see where the rationale is. ... Eventually you run out of other people’s money,” he said. Meadows was among Republicans who voted in late December for their party’s debt-financed tax overhaul, which is expected to balloon the federal budget deficit and add about $1.5 trillion over 10 years to the $20 trillion national debt. “It’s interesting to hear Mark talk about fiscal responsibility,” Democratic U.S. Representative Joseph Crowley said on CBS. Crowley said the Republican tax bill would require the  United States to borrow $1.5 trillion, to be paid off by future generations, to finance tax cuts for corporations and the rich. “This is one of the least ... fiscally responsible bills we’ve ever seen passed in the history of the House of Representatives. I think we’re going to be paying for this for many, many years to come,” Crowley said. Republicans insist the tax package, the biggest U.S. tax overhaul in more than 30 years,  will boost the economy and job growth. House Speaker Paul Ryan, who also supported the tax bill, recently went further than Meadows, making clear in a radio interview that welfare or “entitlement reform,” as the party often calls it, would be a top Republican priority in 2018. In Republican parlance, “entitlement” programs mean food stamps, housing assistance, Medicare and Medicaid health insurance for the elderly, poor and disabled, as well as other programs created by Washington to assist the needy. Democrats seized on Ryan’s early December remarks, saying they showed Republicans would try to pay for their tax overhaul by seeking spending cuts for social programs. But the goals of House Republicans may have to take a back seat to the Senate, where the votes of some Democrats will be needed to approve a budget and prevent a government shutdown. Democrats will use their leverage in the Senate, which Republicans narrowly control, to defend both discretionary non-defense programs and social spending, while tackling the issue of the “Dreamers,” people brought illegally to the country as children. Trump in September put a March 2018 expiration date on the Deferred Action for Childhood Arrivals, or DACA, program, which protects the young immigrants from deportation and provides them with work permits. The president has said in recent Twitter messages he wants funding for his proposed Mexican border wall and other immigration law changes in exchange for agreeing to help the Dreamers. Representative Debbie Dingell told CBS she did not favor linking that issue to other policy objectives, such as wall funding. “We need to do DACA clean,” she said.  On Wednesday, Trump aides will meet with congressional leaders to discuss those issues. That will be followed by a weekend of strategy sessions for Trump and Republican leaders on Jan. 6 and 7, the White House said. Trump was also scheduled to meet on Sunday with Florida Republican Governor Rick Scott, who wants more emergency aid. The House has passed an $81 billion aid package after hurricanes in Florida, Texas and Puerto Rico, and wildfires in California. The package far exceeded the $44 billion requested by the Trump administration. The Senate has not yet voted on the aid.

In [ ]:
manual_testing(news_article)

'\n\nLR Prediction : It is a genuine news\nGBC Prediction : It is a genuine news\nRFC Prediction : It is a genuine news'